#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from final_with_arithematic.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 18 "final_with_arithematic.y"

	
 #include <iostream> 
 #include <string>
 #include <map>
 #include <cstdlib>
 #include <cstdio>
 
 using namespace std;

 map <string,string> var;	//symbol table to store the name & type of variables defined ( 2-columns indexed by name )
 FILE *fin, *fout;		//File pointers ( Source File : *fin; Target File : *fout )

 int if_count = 0;         	//count the no of IF's so can be indented appropriately
 int if_block_count = 0;	//to check whether a new if-block has started
 int for_count = 0;		//count the no of FOR's so can be indented appropriately
 int for_block_count = 0;       //to check whether a new for-block has started
 int inblock = -1;		//to check whether we are inside a block ( -1 : since main is also a block but we dont need that to indent )
 char c = ' ';			//block demarcation character

 void yyerror(const char *s);	//overridden function: any error is passed as string to this function and the execution terminated
 extern int yylex();		//invoking the LEX parser to return the scanned lexemes as tokens


#line 46 "final_with_arithematic.y"
typedef union				//The data types to be used for arributes of production variables are defined as UNION
{
  string * sval;
  int  cval;
  struct			//A structure of attribute values for production symnols that need > 1 attributes
  { 
    string * type;
    string * value;
  } type_value;			//Name of the attribute structure is type_value
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	INCLUDE	258
#define	HEADER	259
#define	HEAD_END	260
#define	MAIN	261
#define	TYPE	262
#define	ID	263
#define	RETURN	264
#define	VAL	265
#define	EQUAL	266
#define	CIN	267
#define	IN	268
#define	COUT	269
#define	OUT	270
#define	OP	271
#define	IF	272
#define	ROP	273
#define	CLOSE_BRACE	274
#define	ELSE	275
#define	SEMICOLON	276
#define	OPEN_CURLY	277
#define	CLOSE_CURLY	278
#define	FOR	279
#define	PLUSPLUS	280
#define	MINUSMINUS	281


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int INCLUDE;
static const int HEADER;
static const int HEAD_END;
static const int MAIN;
static const int TYPE;
static const int ID;
static const int RETURN;
static const int VAL;
static const int EQUAL;
static const int CIN;
static const int IN;
static const int COUT;
static const int OUT;
static const int OP;
static const int IF;
static const int ROP;
static const int CLOSE_BRACE;
static const int ELSE;
static const int SEMICOLON;
static const int OPEN_CURLY;
static const int CLOSE_CURLY;
static const int FOR;
static const int PLUSPLUS;
static const int MINUSMINUS;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,INCLUDE=258
	,HEADER=259
	,HEAD_END=260
	,MAIN=261
	,TYPE=262
	,ID=263
	,RETURN=264
	,VAL=265
	,EQUAL=266
	,CIN=267
	,IN=268
	,COUT=269
	,OUT=270
	,OP=271
	,IF=272
	,ROP=273
	,CLOSE_BRACE=274
	,ELSE=275
	,SEMICOLON=276
	,OPEN_CURLY=277
	,CLOSE_CURLY=278
	,FOR=279
	,PLUSPLUS=280
	,MINUSMINUS=281


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::INCLUDE=258;
const int YY_parse_CLASS::HEADER=259;
const int YY_parse_CLASS::HEAD_END=260;
const int YY_parse_CLASS::MAIN=261;
const int YY_parse_CLASS::TYPE=262;
const int YY_parse_CLASS::ID=263;
const int YY_parse_CLASS::RETURN=264;
const int YY_parse_CLASS::VAL=265;
const int YY_parse_CLASS::EQUAL=266;
const int YY_parse_CLASS::CIN=267;
const int YY_parse_CLASS::IN=268;
const int YY_parse_CLASS::COUT=269;
const int YY_parse_CLASS::OUT=270;
const int YY_parse_CLASS::OP=271;
const int YY_parse_CLASS::IF=272;
const int YY_parse_CLASS::ROP=273;
const int YY_parse_CLASS::CLOSE_BRACE=274;
const int YY_parse_CLASS::ELSE=275;
const int YY_parse_CLASS::SEMICOLON=276;
const int YY_parse_CLASS::OPEN_CURLY=277;
const int YY_parse_CLASS::CLOSE_CURLY=278;
const int YY_parse_CLASS::FOR=279;
const int YY_parse_CLASS::PLUSPLUS=280;
const int YY_parse_CLASS::MINUSMINUS=281;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		88
#define	YYFLAG		-32768
#define	YYNTBASE	27

#define YYTRANSLATE(x) ((unsigned)(x) <= 281 ? yytranslate[x] : 46)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     5,    10,    14,    15,    21,    24,    26,    27,
    29,    31,    33,    35,    37,    39,    41,    45,    50,    54,
    58,    61,    65,    69,    72,    79,    84,    89,    96,   103,
   110,   114,   118,   126,   129,   132,   135,   138,   143,   147,
   151,   155,   159,   163
};

static const short yyrhs[] = {    28,
    30,     0,    29,     0,     3,     4,     5,    29,     0,     3,
     4,     5,     0,     0,     6,    22,    31,     9,    23,     0,
    32,    31,     0,    32,     0,     0,    33,     0,    34,     0,
    35,     0,    37,     0,    44,     0,    39,     0,    42,     0,
     7,     8,    21,     0,     8,    11,    10,    21,     0,    12,
    36,    21,     0,    13,     8,    36,     0,    13,     8,     0,
    14,    38,    21,     0,    15,     8,    38,     0,    15,     8,
     0,    17,    41,    19,    32,    20,    32,     0,    17,    41,
    19,    32,     0,    17,    41,    19,    40,     0,    17,    41,
    19,    40,    20,    40,     0,    17,    41,    19,    40,    20,
    32,     0,    17,    41,    19,    32,    20,    40,     0,    22,
    31,    23,     0,     8,    18,     8,     0,    24,    34,    41,
    21,    43,    19,    32,     0,     8,    25,     0,    25,     8,
     0,    26,     8,     0,     8,    26,     0,     8,    11,    45,
    21,     0,     8,    16,    45,     0,    10,    16,    45,     0,
     8,    16,     8,     0,     8,    16,    10,     0,    10,    16,
     8,     0,    10,    16,    10,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   105,   111,   118,   122,   126,   130,   139,   143,   147,   150,
   152,   154,   156,   158,   165,   180,   196,   212,   232,   241,
   248,   256,   266,   273,   283,   301,   314,   322,   334,   348,
   364,   412,   424,   443,   447,   451,   455,   461,   471,   481,
   489,   500,   511,   522
};

static const char * const yytname[] = {   "$","error","$illegal.","INCLUDE",
"HEADER","HEAD_END","MAIN","TYPE","ID","RETURN","VAL","EQUAL","CIN","IN","COUT",
"OUT","OP","IF","ROP","CLOSE_BRACE","ELSE","SEMICOLON","OPEN_CURLY","CLOSE_CURLY",
"FOR","PLUSPLUS","MINUSMINUS","prog","header","head_append","main","body","statement",
"decl","initial","input","input1","output","output1","if_else","block","condition",
"for_loop","increment","arith_expr","expression",""
};
#endif

static const short yyr1[] = {     0,
    27,    28,    29,    29,    29,    30,    31,    31,    31,    32,
    32,    32,    32,    32,    32,    32,    33,    34,    35,    36,
    36,    37,    38,    38,    39,    39,    39,    39,    39,    39,
    40,    41,    42,    43,    43,    43,    43,    44,    45,    45,
    45,    45,    45,    45
};

static const short yyr2[] = {     0,
     2,     1,     4,     3,     0,     5,     2,     1,     0,     1,
     1,     1,     1,     1,     1,     1,     3,     4,     3,     3,
     2,     3,     3,     2,     6,     4,     4,     6,     6,     6,
     3,     3,     7,     2,     2,     2,     2,     4,     3,     3,
     3,     3,     3,     3
};

static const short yydefact[] = {     5,
     0,     0,     2,     0,     0,     1,     4,     9,     3,     0,
     0,     0,     0,     0,     0,     0,     8,    10,    11,    12,
    13,    15,    16,    14,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     7,    17,     0,     0,     0,
    21,    19,    24,    22,     0,     0,     0,     0,     6,     0,
     0,    18,    38,    20,    23,    32,     9,    26,    27,     0,
     0,    41,    42,    39,    43,    44,    40,     0,     0,     0,
     0,     0,     0,     0,    31,    25,    30,    29,    28,    34,
    37,    35,    36,     0,    33,     0,     0,     0
};

static const short yydefgoto[] = {    86,
     2,     3,     6,    16,    17,    18,    19,    20,    28,    21,
    30,    22,    59,    32,    23,    74,    24,    40
};

static const short yypact[] = {     6,
    10,    12,-32768,    17,    15,-32768,     6,    19,-32768,    21,
    27,    31,    30,    24,    38,    39,    19,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,    26,     2,    41,    29,    43,    32,
    34,    35,    44,    24,    33,-32768,-32768,    42,   -13,    36,
    31,-32768,    30,-32768,    51,    -1,    50,    40,-32768,     7,
    20,-32768,-32768,-32768,-32768,-32768,    19,    45,    46,    47,
    -6,    42,    48,-32768,    42,    48,-32768,    49,    -1,    -1,
   -21,    54,    55,    52,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,    19,-32768,    67,    69,-32768
};

static const short yypgoto[] = {-32768,
-32768,    63,-32768,   -17,   -45,-32768,    58,-32768,    37,-32768,
    53,-32768,   -35,    56,-32768,-32768,-32768,    -9
};


#define	YYLAST		96


static const short yytable[] = {    36,
    58,    71,    51,    80,    81,    10,    11,    52,     1,    38,
    12,    39,    13,     4,    62,    14,    63,     5,    72,    73,
    57,     7,    15,    76,    78,    10,    11,    65,    25,    66,
    12,    31,    13,    77,    79,    14,     8,    26,    85,    68,
    64,    67,    15,    27,    29,    33,    37,    35,    41,    42,
    43,    45,    44,    46,    47,    49,    53,    50,    56,    60,
    61,    82,    83,    51,    69,    70,    87,    52,    88,     9,
    84,    75,    34,     0,     0,     0,     0,    54,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,    48,
     0,     0,     0,     0,     0,    55
};

static const short yycheck[] = {    17,
    46,     8,    16,    25,    26,     7,     8,    21,     3,     8,
    12,    10,    14,     4,     8,    17,    10,     6,    25,    26,
    22,     5,    24,    69,    70,     7,     8,     8,     8,    10,
    12,     8,    14,    69,    70,    17,    22,    11,    84,    57,
    50,    51,    24,    13,    15,     8,    21,     9,     8,    21,
     8,    18,    21,    19,    11,    23,    21,    16,     8,    10,
    21,     8,     8,    16,    20,    20,     0,    21,     0,     7,
    19,    23,    15,    -1,    -1,    -1,    -1,    41,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    34,
    -1,    -1,    -1,    -1,    -1,    43
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 106 "final_with_arithematic.y"
{
			   std :: cout << "YAY...Code Successfully Parsed and Indented!!!\n"; 
			;
    break;}
case 2:
#line 112 "final_with_arithematic.y"
{
			   for(int i = 0 ; i <(*yyvsp[0].sval).size(); i++)     // printing out the characters appended in head from earlier productions
			     fprintf(fout,"%c",(*yyvsp[0].sval)[i]);	     // printing in the output file - fout
			;
    break;}
case 3:
#line 119 "final_with_arithematic.y"
{
			   *yyval.sval ="#include <" + (*yyvsp[-2].sval)+ ">\n" + (*yyvsp[0].sval); // Appending the components in attribute of head of production
			;
    break;}
case 4:
#line 123 "final_with_arithematic.y"
{
			   *yyval.sval = "#include <" + (*yyvsp[-1].sval)+ ">\n" ;
			;
    break;}
case 5:
#line 126 "final_with_arithematic.y"
{;;
    break;}
case 6:
#line 131 "final_with_arithematic.y"
{
			  fprintf(fout,"%s\n%s  \n",(*yyvsp[-4].sval).c_str(),(*yyvsp[-3].sval).c_str()); // the string in file is printed as c-string
			  for(int i = 0 ; i <(*yyvsp[-2].sval).size(); i++)			  // The body is printed using this loop
			    fprintf(fout,"%c",(*yyvsp[-2].sval)[i]); 
			  fprintf(fout,"\n  %s\n%s",(*yyvsp[-1].sval).c_str(),(*yyvsp[0].sval).c_str()); // return 0; & '}' are appended at the end of program
			;
    break;}
case 7:
#line 140 "final_with_arithematic.y"
{
			   *yyval.sval = *yyvsp[-1].sval + *yyvsp[0].sval;
			;
    break;}
case 8:
#line 144 "final_with_arithematic.y"
{
			   *yyval.sval = *yyvsp[0].sval ;
			;
    break;}
case 9:
#line 147 "final_with_arithematic.y"
{;;
    break;}
case 10:
#line 151 "final_with_arithematic.y"
{ yyval.sval = yyvsp[0].sval; ;
    break;}
case 11:
#line 153 "final_with_arithematic.y"
{ yyval.sval = yyvsp[0].sval; ;
    break;}
case 12:
#line 155 "final_with_arithematic.y"
{ yyval.sval = yyvsp[0].sval; ;
    break;}
case 13:
#line 157 "final_with_arithematic.y"
{ yyval.sval = yyvsp[0].sval; ;
    break;}
case 14:
#line 159 "final_with_arithematic.y"
{ 
			  yyval.sval = yyvsp[0].sval;
			  if(if_count != 0) //Indicating a new block is getting started after a statement within if
                            c = ';';	    // this might be the end statement of a block so demarcating by setting 'c'	
			;
    break;}
case 15:
#line 165 "final_with_arithematic.y"
{		   			  // statement can be an If-else ( Nested or individual ) block
			  if(inblock != 0 && if_block_count == 0) // when the IF is inside a block ( {} ) but no block is there within
			    if_count--;
		          if(inblock == 0)   		          //when not inside a block we need to decrement if_count when a IF is reduced
			    if_count--;
                          if(if_block_count ==1 && if_count == 0) // when all if's are reduced but due to lookahead an if has been counted
							          // but will not be done afterwards so setting the seen if
                          {
			    if_count = 1;
			    if_block_count = 0;
			  }
			  
			  yyval.sval = yyvsp[0].sval;	  		          //the value of if_else block is assigned to statement and cascaded up	
			;
    break;}
case 16:
#line 180 "final_with_arithematic.y"
{		   			  // statement can be a FOR ( Nested or individual ) block
		         if(inblock != 0 && for_block_count == 0) // when the FOR loop is inside a block ( {} ) but no block is there within
			   for_count--;
		         if(inblock == 0)   		           //when not inside a block we need to decrement for_count when a IF is reduced
			   for_count--;
                         if(for_block_count ==1 && for_count == 0) // when all FOR's are reduced but due to lookahead a FOR has been counted
							           // but will not be done afterwards so setting the seen FOR
                         {
			   for_count = 1;
			   for_block_count = 0;
			 }
			 
			 yyval.sval = yyvsp[0].sval;	  		           //the value of FOR block is assigned to statement and cascaded up	
			;
    break;}
case 17:
#line 197 "final_with_arithematic.y"
{
			  if(var.find(*yyvsp[-1].sval) != var.end())   //variable already defined so prompt an error
			    yyerror("Input Variable Already Defined\n");

                          var[*yyvsp[-1].sval] = *yyvsp[-2].sval;		   //storing the type of variable in symbol-table(var)
                         
			  *yyval.sval = ("  ") + (*yyvsp[-2].sval) + " " + (*yyvsp[-1].sval) + " ;\n";
                           
			  if(if_count != 0)     	   // this might be the end statement of a block so demarcating by setting 'c'
                           c = ';';

			;
    break;}
case 18:
#line 213 "final_with_arithematic.y"
{ 
			   if(var.find(*yyvsp[-3].sval) == var.end() )      // variable not defined previously
			     yyerror("Input Variable Not Defined\n");
                             
			   if( 					// checking LHS and RHS have same type for initialization
			       (var[*yyvsp[-3].sval] == "int" && *(yyvsp[-1].type_value.type) == "int")    || 
			       (var[*yyvsp[-3].sval] == "char" && *(yyvsp[-1].type_value.type) == "char")  || 
			       (var[*yyvsp[-3].sval] == "float" && *(yyvsp[-1].type_value.type) == "float") 
			     )
			     *yyval.sval = ("  ") + (*yyvsp[-3].sval) + (" = ") + (*(yyvsp[-1].type_value.value)) + " ;\n"  ;
			   else					// type conflict print the error
			     yyerror("Initialisation Error : LHS-RHS type conflict\n"); 
			     
                           if(if_count != 0)  			// this might be the end statement of a block so demarcating by setting 'c'
                           c = ';';
			;
    break;}
case 19:
#line 233 "final_with_arithematic.y"
{ 
			   *yyval.sval = "  cin" + *yyvsp[-1].sval + " ;\n"; 	// the value is assigned to the head so that concatenated string can be cascaded 
 			   
                           if(if_count != 0)  			// this might be the end statement of a block so demarcating by setting 'c'
                           c = ';';
			;
    break;}
case 20:
#line 242 "final_with_arithematic.y"
{
			   if( var.find(*yyvsp[-1].sval) == var.end() )	// the variable is not declared earlier
			     yyerror("Variable in cin has not been declared previously\n");
			   
			   *yyval.sval =" " + *yyvsp[-2].sval + " " + *yyvsp[-1].sval + *yyvsp[0].sval;
			;
    break;}
case 21:
#line 249 "final_with_arithematic.y"
{ 
			   if( var.find(*yyvsp[0].sval) == var.end() )	// the variable is not declared earlier
			     yyerror("Variable in cin has not been declared previously\n");
			  *yyval.sval = " " + *yyvsp[-1].sval +" " + *yyvsp[0].sval; 
			;
    break;}
case 22:
#line 257 "final_with_arithematic.y"
{
			   *yyval.sval = "  cout" + *yyvsp[-1].sval + " ;\n";	// the cout statement is assigned to head so that can be cascaded up
			   
                           if(if_count != 0)  			// this might be the end statement of a block so demarcating by setting 'c' 
                           c = ';';

			;
    break;}
case 23:
#line 267 "final_with_arithematic.y"
{
			   if( var.find(*yyvsp[-1].sval) == var.end() )	// the variable is not declared earlier
			     yyerror("Variable in cout has not been declared previously\n");

			   *yyval.sval = " " + *yyvsp[-2].sval + " " + *yyvsp[-1].sval + *yyvsp[0].sval;
			;
    break;}
case 24:
#line 274 "final_with_arithematic.y"
{
			   if( var.find(*yyvsp[0].sval) == var.end() )	// the variable is not declared earlier
			     yyerror("Variable in cout has not been declared\n");

			   *yyval.sval = " " + *yyvsp[-1].sval +" " + *yyvsp[0].sval; 
			;
    break;}
case 25:
#line 284 "final_with_arithematic.y"
{
			   for(int i = 0; i < 2*if_count; i++)	// indenting the if and the statements accordingly with if_count
			   {  
			     *yyvsp[-5].sval = " " + *yyvsp[-5].sval; *yyvsp[-1].sval = " " + *yyvsp[-1].sval;
                              
			      if ( (*yyvsp[-2].sval)[2*(if_count+1)] != 'i' && (*yyvsp[-2].sval)[2*(if_count+1)+1] != 'f')  //if the following statement is if we need 													    //not increment their space
			        *yyvsp[-2].sval = " " + *yyvsp[-2].sval; 
			      
			      if ( (*yyvsp[0].sval)[2*(if_count+1)] != 'i' && (*yyvsp[0].sval)[2*(if_count+1)+1] != 'f')  // the cascated if statements need not be 
												    // indented 
			        *yyvsp[0].sval = " " + *yyvsp[0].sval;
                           }
				
			   *yyval.sval = *yyvsp[-5].sval + *yyvsp[-4].sval + *yyvsp[-3].sval + "\n" + *yyvsp[-2].sval + *yyvsp[-1].sval + "\n" + *yyvsp[0].sval; 		   // (if (a < b) \n statement(\n already in  
												   // statement) else\n statement appended
				
			;
    break;}
case 26:
#line 302 "final_with_arithematic.y"
{  
			   for(int i = 0; i < 2*if_count; i++)	// indenting the if and the statements accordingly with if_count
			    { 
			     *yyvsp[-3].sval = " " + *yyvsp[-3].sval;
			     
			     if ( (*yyvsp[0].sval)[2*(if_count+1)] != 'i' && (*yyvsp[0].sval)[2*(if_count+1)+1] != 'f')  //if the following statement is if we need 													   //not increment their space
			        *yyvsp[0].sval = " " + *yyvsp[0].sval; 	
			    }

			   *yyval.sval = *yyvsp[-3].sval + *yyvsp[-2].sval + *yyvsp[-1].sval + "\n" + *yyvsp[0].sval; 		  			   // (if (a < b) \n statement appended 

			;
    break;}
case 27:
#line 315 "final_with_arithematic.y"
{
			   for(int i = 0; i < 2*if_count; i++)	// indenting the if and the statements accordingly with if_count
			     *yyvsp[-3].sval = " " + *yyvsp[-3].sval; 

			   *yyval.sval = *yyvsp[-3].sval + *yyvsp[-2].sval + *yyvsp[-1].sval + "\n" + *yyvsp[0].sval;	// (if (a < b)\n { block } appended
			;
    break;}
case 28:
#line 323 "final_with_arithematic.y"
{  			   
			   for(int i = 0; i < 2*if_count; i++)	// indenting the if and the statements accordingly with if_count
			   {
			     *yyvsp[-5].sval = " " + *yyvsp[-5].sval;
			     *yyvsp[-1].sval = " " + *yyvsp[-1].sval;
			   } 

			   *yyval.sval = *yyvsp[-5].sval + *yyvsp[-4].sval + *yyvsp[-3].sval + "\n" + *yyvsp[-2].sval + *yyvsp[-1].sval+ "\n" + *yyvsp[0].sval ; // ( if (a < b)\n {block}(\n already in block) else\n {block}

			;
    break;}
case 29:
#line 335 "final_with_arithematic.y"
{  
			   for(int i = 0; i < 2*if_count; i++)	// indenting the if and the statements accordingly with if_count
			   {
			     *yyvsp[-5].sval = " " + *yyvsp[-5].sval;
			     *yyvsp[-1].sval = " " + *yyvsp[-1].sval;
                                 
			     if ( (*yyvsp[0].sval)[2*(if_count+1)] != 'i' && (*yyvsp[0].sval)[2*(if_count+1)+1] != 'f' ) //in statement part IF : need not be indented
			       *yyvsp[0].sval = " " + *yyvsp[0].sval;
			   } 
                           
			   *yyval.sval = *yyvsp[-5].sval + *yyvsp[-4].sval + *yyvsp[-3].sval + "\n" + *yyvsp[-2].sval + *yyvsp[-1].sval+ "\n" + *yyvsp[0].sval ; // ( if (a < b)\n {block}(\n already there) else\n statement
			   
			;
    break;}
case 30:
#line 349 "final_with_arithematic.y"
{  
			   for(int i = 0; i < 2*if_count; i++)	// indenting the if and the statements accordingly with if_count
			   {
			     *yyvsp[-5].sval = " " + *yyvsp[-5].sval;
			     *yyvsp[-1].sval = " " + *yyvsp[-1].sval;
                               
			     if ( (*yyvsp[-2].sval)[2*(if_count+1)] != 'i' && (*yyvsp[-2].sval)[2*(if_count+1)+1] != 'f') //in statement part IF : need not be indented
			       *yyvsp[-2].sval = " " + *yyvsp[-2].sval;
			   } 

			   *yyval.sval = *yyvsp[-5].sval + *yyvsp[-4].sval + *yyvsp[-3].sval + "\n" + *yyvsp[-2].sval + *yyvsp[-1].sval+ "\n" + *yyvsp[0].sval ; // ( if (a < b)\n statement(\n already there) else\n {block}

			;
    break;}
case 31:
#line 365 "final_with_arithematic.y"
{ 
			   string block_statements, open_curly, close_curly, line; //block_statements : contain full body after correct indent
			   int no_line_indent = 0, block_no_indent = 0, block_end_found = 0; 

                           for( int j = 0 ; j < 2 * if_count ; j++)	 //indenting the  { & } accordingly to the block
                           { 
			     line = " " + line;			    	 // line contains each line of body in each iteration
			     open_curly = " " + open_curly ;
			     close_curly = " "+ close_curly;
			   }
	 
			   for(int i = 0 ; i < (*yyvsp[-1].sval).size() ; i++ )
			   {
			     if( (*yyvsp[-1].sval)[i] == 'i' && (*yyvsp[-1].sval)[i+1] == 'f' || (*yyvsp[-1].sval).find(" else ") != -1 ) //if & else are already indented 
			       no_line_indent = 2;			  // taken 2 becos the next statement will be indented already

			     if( (*yyvsp[-1].sval)[i] == '{' ) 			//blocks are already indented - opening of block
			       block_no_indent ++;

			     if( (*yyvsp[-1].sval)[i] == '}' )  			//closing of block but for that iteration it need be there
			       block_end_found = 1;
                               
			     if( (*yyvsp[-1].sval)[i] != '\n' )			//append the characters in line until '\n'
                             	 line += (*yyvsp[-1].sval)[i];
                             else
                             {
                               line += (*yyvsp[-1].sval)[i];			//appending \n to last charater of line
				 
			       if(no_line_indent > 0 || block_no_indent > 0) //they needed no indentation to strip off the extra added
	                         line = line.substr(2*if_count);
				
			       block_statements += line;		//append the line in correct indented body
			       line = "";				
                               for( int j = 0 ; j < 2 * if_count ; j++) //appending the needed space at the beginning of line
                                 line = " " + line;
				
			       no_line_indent--;			//needs to be decreased because one line is taken care of
			       if(block_end_found == 1)			//if block end is found then indentation needs to be decreased
				 block_no_indent--;
                             }
			   }

                           *yyval.sval = open_curly + *yyvsp[-2].sval + "\n" + block_statements + close_curly + *yyvsp[0].sval + "\n"; // { \n body (\n aready) }\n 
			;
    break;}
case 32:
#line 413 "final_with_arithematic.y"
{
			   if(var.find(*yyvsp[-2].sval) == var.end()) 	// variable in condition not defined previously
			     yyerror("Variable in condition Not Defined\n");

			   if(var.find(*yyvsp[0].sval) == var.end() ) 	// variable in condition not defined previously
			     yyerror("Variable in condition Not Defined\n");

			   *yyval.sval = *yyvsp[-2].sval + " " + *yyvsp[-1].sval + " " + *yyvsp[0].sval;   // ( eg : a(space)<(space)b i.e. a < b ) 
			;
    break;}
case 33:
#line 425 "final_with_arithematic.y"
{  
			   for(int i = 0; i < 2*for_count; i++)	// indenting the FOR and the statements accordingly with for_count
			   { 
			     *yyvsp[-6].sval = " " + *yyvsp[-6].sval;
			     			  	        // FOR's are already indented
			     if ( (*yyvsp[0].sval)[2*(for_count+1)] != 'f' && (*yyvsp[0].sval)[2*(for_count+1)+1] != 'o' && (*yyvsp[0].sval)[2*(for_count+1)+2] != 'r' ) 
			       *yyvsp[0].sval = " " + *yyvsp[0].sval; 		// if statement is not FOR need to be indented accordingly	
			   }

                         string s ; 	// initialization within FOR comes with 2 spaces in beginning so stripping them off
                         for(int i = 2 ; (*yyvsp[-5].sval)[i] != '\n'; i++)
                         s += (*yyvsp[-5].sval)[i];

			   *yyval.sval = *yyvsp[-6].sval + s+ " " + *yyvsp[-4].sval +" " +*yyvsp[-3].sval +" " + *yyvsp[-2].sval + *yyvsp[-1].sval +"\n"+ *yyvsp[0].sval; // for (i = 0 ; i < c; i++)

			;
    break;}
case 34:
#line 444 "final_with_arithematic.y"
{
			  *yyval.sval = *yyvsp[-1].sval + *yyvsp[0].sval;
			;
    break;}
case 35:
#line 448 "final_with_arithematic.y"
{
			  *yyval.sval = *yyvsp[-1].sval + *yyvsp[0].sval;
			;
    break;}
case 36:
#line 452 "final_with_arithematic.y"
{ 
			  *yyval.sval = *yyvsp[-1].sval + *yyvsp[0].sval;
			;
    break;}
case 37:
#line 456 "final_with_arithematic.y"
{
			  *yyval.sval = *yyvsp[-1].sval + *yyvsp[0].sval;
			;
    break;}
case 38:
#line 462 "final_with_arithematic.y"
{
			  if(var.find(*yyvsp[-3].sval) == var.end() ) 	//variable not defined previously
			     yyerror("Input Variable in Arithematic Expression Not Defined\n");

			  if( var[*yyvsp[-3].sval] != "void" )
			    *yyval.sval = "  " + *yyvsp[-3].sval + " = " + *yyvsp[-1].sval + " ;\n";  // type ( a = b + c - 4 ... ;\n) 
			;
    break;}
case 39:
#line 472 "final_with_arithematic.y"
{
			  if( var.find(*yyvsp[-2].sval) == var.end() ) 	//variable not defined previously
			     yyerror("RHS variable in Arithematic Expression Not Defined\n");
			  
			  if( var[*yyvsp[-2].sval] != "void" )
			    *yyval.sval = *yyvsp[-2].sval + " " + *yyvsp[-1].sval + " " + *yyvsp[0].sval;	// type ( (space)id +(expression that already has space) )
			  else
			     yyerror("Invalid Arithematic Operations (void) not allowed"); // the type of operands does not match for operation
			;
    break;}
case 40:
#line 482 "final_with_arithematic.y"
{
			  if( *(yyvsp[-2].type_value.type) != "void" )
			    *yyval.sval = *(yyvsp[-2].type_value.value) + " " + *yyvsp[-1].sval + " " + *yyvsp[0].sval;	// type ( (space)value +(expression that already has space) )
			  else
			     yyerror("Invalid Arithematic Operations (void) not allowed"); // the type of operands does not match for operation
			;
    break;}
case 41:
#line 490 "final_with_arithematic.y"
{
			   if(var.find(*yyvsp[-2].sval) == var.end() || var.find(*yyvsp[0].sval) == var.end()) 	//variable not defined previously
			     yyerror("RHS variable in Arithematic Expression Not Defined\n");

			   if( (var[*yyvsp[-2].sval] != "void") && (var[*yyvsp[0].sval] != "void") )   // cheking the type of variables for compatibility with OP
			     *yyval.sval = *yyvsp[-2].sval + " " + *yyvsp[-1].sval + " " + *yyvsp[0].sval; // type ( (space)id operator id)
			   else
			     yyerror("Invalid Arithematic Operations (void) not allowed"); // the type of operands does not match for operation
			;
    break;}
case 42:
#line 501 "final_with_arithematic.y"
{
			   if( var.find(*yyvsp[-2].sval) == var.end() ) 	//variable not defined previously
			     yyerror("RHS variable in Arithematic Expression Not Defined\n");

			   if( (var[*yyvsp[-2].sval] != "void") && (*(yyvsp[0].type_value.type) != "void") ) // cheking the type of variables for compatibility with OP
			     *yyval.sval = *yyvsp[-2].sval + " " + *yyvsp[-1].sval + " " + *(yyvsp[0].type_value.value);	// type ( (space)id operator value)
			   else
			     yyerror("Invalid Arithematic Operations");		// the type of operands does not match for operation
			;
    break;}
case 43:
#line 512 "final_with_arithematic.y"
{
			   if(var.find(*yyvsp[0].sval) == var.end() ) 	//variable not defined previously
			     yyerror("RHS variable in Arithematic Expression Not Defined\n");

			   if( (*(yyvsp[-2].type_value.type) != "void") && (var[*yyvsp[0].sval] != "void") ) // cheking the type of variables for compatibility with OP
			     *yyval.sval = *(yyvsp[-2].type_value.value) + " " + *yyvsp[-1].sval + " " + *yyvsp[0].sval;	// type ( (space)value operator id)
			   else
			     yyerror("Invalid Arithematic Operations");		// the type of operands does not match for operation

			;
    break;}
case 44:
#line 523 "final_with_arithematic.y"
{
			   if( (*(yyvsp[-2].type_value.type) != "void") && (*(yyvsp[0].type_value.type) != "void") ) // cheking the type of variables for compatibility with OP
			     *yyval.sval = *(yyvsp[-2].type_value.value) + " " + *yyvsp[-1].sval + " " + *(yyvsp[0].type_value.value);	// type ( (space)value operator value)
			   else
			     yyerror("Invalid Arithematic Operations");		  // the type of operands does not match for operation

			;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 534 "final_with_arithematic.y"

  #include <stdio.h>

  extern int yyparse(void);		// decleration of the function that parses and build the parse tree
  extern FILE *yyin;			// input stream pointer

  int main() 
  {   
    fin = fopen("try_file.cpp","r"); 	// opening the source file
    if (!fin)
    {
      std::cout<<"Can't open file!";
      return -1;
    }
  
    fout = fopen("target.cpp", "w");	// opening the target file
    yyin = fin;    			// pointing the input stream pointer to the input file pointer
    do{
      yyparse();			// calling the yyparse function
      }while (!feof(yyin));
    
    fclose(fout);
    return 1;
  }
   
  void yyerror(const char *s)		// function that is called whenever an error is encounted. Prints the message & exits
  {
    std::cout<<"Parse error : " << s <<std::endl;
    exit(0);
  }


